version: "3.9"
    
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
  
  mysql-server:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "5000:80"
  pmm-data:
    image: percona/pmm-server:2
    container_name: pmm-data
    command: "/bin/true"
    volumes:
      - /srv/pmm-data:/srv

  pmm-server:
    image: percona/pmm-server:2
    container_name: pmm-server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pmm-data
    volumes_from:
      - pmm-data

  pmm-client:
    image: percona/pmm-client:2
    container_name: pmm-client
    volumes:
      - /srv/pmm-client-data:/srv
    # ports: 
    #   - "80:80"
    
volumes:
  mysql-data:

